### PR TITLE
Added without inner lines prop for line chart

### PR DESCRIPTION
**Pull request by gish94**
screen shot 2019-02-08 at 23 06 39

### CODE REVIEW

**Comment by olegberman** [comment]
This is sweet dude, @Hermanya review? :-)

**Comment by Hermanya** [comment]
Looks okay, please update the README to include this prop in the props table for the line chart.

**Comment by gish94** [comment]
@Hermanya there are also 2 other props "withShadow" and "withDots" which are also not in the props table. 
screen shot 2019-02-09 at 15 26 54

**Comment by Hermanya** [comment]
👍 thanks for the PR
I changed `withoutInnerLines` to `withInnerLines` for consistency.
So, in your case it's `withInnerLines={false}`

**Pull request merged**
