### PR TITLE
Ability to add custom segments on the Y-Axis

### PR DESCRIPTION
**Pull request by alexandargyurov**
## Allows custom segments to be added on the Y-Axis

This PR allows the ability to add custom Y-Axis segments.

Before there was a hardcoded value of `4`, now, the user can give a `segments` parameter which will dynamically change the horizontal lines on the graph and evenly distribute the labels as well.

I believe this also closes issues: #70 and partially #122.

This is for `Line Graphs` & `Bar Charts`. An improvement to this would be to have the ability to add a Max Value for the Y-Axis however that can be a separate PR.

Feedback and comments welcome! I did this as I needed 5 segments for a graph!

### CODE REVIEW

**Comment by Hermanya** [comment]
Nice! Thank you! This is now available in 4.4.0

**Comment by gypsicoder** [comment]
@alexandargyurov Is there any way to set custom segment values? For example I want to keep 4 segments with 1000, 5000, 10000, 20000. Is it possible? Current the segments are calculated from data.

**Comment by alexandargyurov** [comment]
Hey @gypsicoder, I don't believe it's currently possible with the current implementation. I too ran into this issue but unfortunately did not have the time to look into it. It might be worth having a wider discussion on what the best approach is to do this.

**Comment by molchanovskiy** [comment]
Any updates on this one?
For example I want to keep 4 segments with 1000, 5000, 10000, 20000. Is it possible? Current the segments are calculated from data.

**Comment by BvdLind** [comment]
@molchanovskiy, @alexandargyurov, @gypsicoder It's possible for `LineCharts` at least if you make use of `yield` and the `formatYLabel` prop. I've answered a question about it here: https://stackoverflow.com/q/63905403/9098350.

**Comment by priyankaEdufund** [comment]
> ## Allows custom segments to be added on the Y-Axis
> This PR allows the ability to add custom Y-Axis segments.
> 
> Before there was a hardcoded value of `4`, now, the user can give a `segments` parameter which will dynamically change the horizontal lines on the graph and evenly distribute the labels as well.
> 
> I believe this also closes issues: #70 and partially #122.
> 
> This is for `Line Graphs` & `Bar Charts`. An improvement to this would be to have the ability to add a Max Value for the Y-Axis however that can be a separate PR.
> 
> Feedback and comments welcome! I did this as I needed 5 segments for a graph!

Thanks, was helpful for me :)

**Comment by priyankaEdufund** [comment]
> @molchanovskiy, @alexandargyurov, @gypsicoder It's possible for the `LineChart` component at least if you make use of `yield` and the `formatYLabel` prop on the `LineChart`. I've answered a question about it here: https://stackoverflow.com/q/63905403/9098350.
> 
> I don't think it's possible for bar charts, since they don't have a prop like `formatYLabel` as far as I'm aware of.
> 
> In case the link the dies, here is a code snippet:
> 
> ```
> function* yLabel() {
>   yield* ['None', 'Low', 'Med', 'High'];
> }
> 
> function App() {
>   const yLabelIterator = yLabel();
> 
>   return (
>     <View>
>       <LineChart
>         data={{
>           labels: ['Mo', 'Tu', 'We', 'Fr', 'Sa', 'Su'],
>           datasets: [
>             {
>               data: [3, 2, 1, 4, 4],
>             },
>             {
>               data: [5, 1, 3, 2],
>             },
>           ],
>         }}
>         segments={3}
>         width={320}
>         height={200}
>         formatYLabel={() => yLabelIterator.next().value}
>         chartConfig={{
>           backgroundColor: 'white',
>           backgroundGradientFrom: 'grey',
>           backgroundGradientTo: 'grey',
>           color: (opacity = 1) => `rgba(255, 255, 255, ${opacity})`,
>           labelColor: (opacity = 1) => `rgba(255, 255, 255, ${opacity})`,
>         }}
>       />
>     </View>
>   );
> }
> 
> export default App;
> ```

Thanks, it was helpful :)

**Pull request merged**
