### PR TITLE
Hide Horizontal and Vertical Labels

### PR DESCRIPTION
**Pull request by rockorama**
https://github.com/indiespirit/react-native-chart-kit/issues/76

### CODE REVIEW

**Comment by Hermanya** [comment]
Looks good, thank you very much @diogoperillo 👍

**Comment by Hermanya** [comment]
this is now available in 3.1.0

**Comment by diogoperillo** [comment]
That's great! Thanks!

**Comment by rafaelsilvestre** [comment]
image

I would like to use the line graph, without the labels ... with the graph taking up the total space. Any solution to solve this?

**Comment by waleedAlmubarak** [comment]
> image
> 
> I would like to use the line graph, without the labels ... with the graph taking up the total space. Any solution to solve this?

Did you find a solution for this ?

**Comment by rafaelsilvestre** [comment]
> > image
> > I would like to use the line graph, without the labels ... with the graph taking up the total space. Any solution to solve this?
> 
> Did you find a solution for this ?

I couldn't solve this problem, the solution was to keep the labels horizontal

**Pull request merged**
