### PR TITLE
Separate withInnerLines and withOuterLines by vertical and horizontal

### PR DESCRIPTION
**Pull request by tangten**
In some cases we just want to show vertical lines or horizontal lines, so I separated `withInnerLines` and `withOuterLines` by 4 new props:
- withVerticalInnerLines
- withHorizontalInnerLines
- withVerticalOuterLines
- withHorizontalOuterLines

### CODE REVIEW

**Comment by Hermanya** [comment]
This change makes the library not backwards compatible. I don't mind the new props, but let's not remove anything from the current api 🙏

**Comment by tangten** [comment]
@Hermanya okay, let me make it backwards compatible :D

**Comment by wolfzer44** [comment]
Do you know when this PR will be merged?

**Comment by tangten** [comment]
@wolfzer44 sorry, I haven't spent time for this one yet

**Pull request closed without merging**
