### PR TITLE
Added getDotProps prop for line chart

### PR DESCRIPTION
**Pull request by rishab1065**
`getDotProps` can be used to pass different `props` for each dot in the line chart.

### CODE REVIEW

**Comment by rishab1065** [comment]
@Hermanya Please review this PR

**Comment by rishab1065** [comment]
@Hermanya Any updates?

**Comment by Hermanya** [comment]
It's been a busy week. I will merge this over the weekend. I'm sorry for the delay.

**Comment by Hermanya** [comment]
Thanks 👍 this is now available in 3.12.0

**Pull request merged**
