### PR TITLE
Fixed BarChart's children have no keys

### PR DESCRIPTION
**Pull request by wuweijian1997**
Fixed BarChart Warning: Each child in a list should have a unique 'key' prop

### CODE REVIEW

**Comment by Hermanya** [comment]
looks like there already was a pr with this change

**Comment by wuweijian1997** [comment]
I don't think it's a good solution.
image

**Comment by Hermanya** [comment]
If you rebase your PR, I'll accept it

**Comment by wuweijian1997** [comment]
Is this ok?

**Comment by Hermanya** [comment]
thank you, this is now available in v6.8.1

**Pull request merged**
