### PR TITLE
Added backgroundColor and backgroundOpacity for line chart & shadow color same as stroke color

### PR DESCRIPTION
**Pull request by WilliamFaga**

### CODE REVIEW

**Comment by Hermanya** [comment]
Thanks, I'll take a look

**Comment by Hermanya** [comment]
@WilliamFaga what is KafraApp?

**Comment by Hermanya** [comment]
I run the sample app locally and I see that a lot of these changes are quite stylistically opinionated. I would prefer the default look to of the sample app to stay the same, and we could make these changes behind some flag props.

Regarding the formatting changes in the line-chart, I have [xo](https://github.com/xojs/xo) set up locally. I should probably add lint-staged, but I never got around to that.

Where did the extra fields in the package.json come from?

**Comment by WilliamFaga** [comment]
> @WilliamFaga what is KafraApp?

It's an app that I'm developing

> I run the sample app locally and I see that a lot of these changes are quite stylistically opinionated. I would prefer the default look to of the sample app to stay the same, and we could make these changes behind some flag props.
> 
> Regarding the formatting changes in the line-chart, I have [xo](https://github.com/xojs/xo) set up locally. I should probably add lint-staged, but I never got around to that.
> 
> Where did the extra fields in the package.json come from?

Oh, it was my error, I copied react-native-chart-kit from my project and paste on the one that I cloned (fork)

And I added that atributes because I couldn't get the chart transparent, if I removed the colors of the chart it would become black, so to work around I had put the backgroundColor and Opacity manually.

It's the first time that I'm doing a PR, so I'm sorry for the mistakes that I'm making

**Pull request closed without merging**
