### PR TITLE
Re-written the whole project in TypeScript

### PR DESCRIPTION
**Pull request by artus9033**
To bring better code maintainability & quality, I re-wrote the project in TypeScript, also adding necessary scripts to `package.json`.

### CODE REVIEW

**Comment by Hermanya** [comment]
Fantastic! It's been long overdue, thank you for taking the time 👍 this is now available in 6.0.0

**Comment by artus9033** [comment]
You're welcome, always happy to contribute to this wonderful library I often make use of as well

**Comment by tayloraleach** [comment]
Updating seems to have disabled the bezier curve prop?

**Comment by artus9033** [comment]
> Updating seems to have disabled the bezier curve prop?

I don't see such a problem - take a look at `src/line-chart/LineChart.tsx:155`
image

**Pull request merged**
